apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgscan
  labels:
    app.kubernetes.io/name: bgscan
    app.kubernetes.io/component: scanner
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - services
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.istio.io"]
    resources:
      - virtualservices
      - destinationrules
      - serviceentries
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - /api
      - /apis
      - /apis/*
      - /api/*
    verbs: ["get"]
